name: Daily Github-Trending

# on:
#   schedule:
#     - cron: "0 2 * * *"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or whatever version you want

    - name: Install dependencies
      run: 
        npm install -g pnpm
        pnpm install

    - name: Run Scraper
      run: |
        pnpm run serve
        # esno scripts/scraper.ts

    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "jscoolso"
        git config --global user.email "sj510915831@163.com""
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
