name: Daily Github-Trending

on:
  schedule:
    - cron: "0 2 * * *"

# on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: MY_ENV

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or whatever version you want

    - name: Install dependencies
      run: 
        npm install

    - name: Run Scraper
      run: |
        npm run scraper
        # esno scripts/scraper.ts

    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "jscoolso"
        git config --global user.email "sj510915831@163.com"
        git remote set-url origin https://x-access-token:${{ secrets.MY_TRENDING_TOKEN }}@github.com/jscoolso/github-trending.git
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
